# Generated by Django 3.1.1 on 2020-10-04 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="title",
        ),
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedule.schedule",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
