# Generated by Django 3.1.1 on 2020-10-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20201004_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Sleep', 'Sleep'), ('Eat', 'Eat'), ('Exercise', 'Exercise'), ('Nap', 'Nap'), ('Leisure', 'Leisure'), ('Other', 'Other')], default='Sleep', max_length=20),
        ),
    ]
